export interface StockEntry {
  symbol: string;
  name: string;
  desc: string;
}

export interface StockCategory {
  id: string;
  name: string;
  icon: string;
  color: string; // tailwind text color
  bg: string;    // tailwind bg for badge
  stocks: StockEntry[];
}

export const STOCK_CATEGORIES: StockCategory[] = [
  {
    id: 'ai-chip',
    name: 'AI Chip & Hardware',
    icon: '🔧',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/15',
    stocks: [
      { symbol: 'NVDA', name: 'NVIDIA', desc: 'GPU สำหรับ AI / Data Center' },
      { symbol: 'AMD', name: 'Advanced Micro Devices', desc: 'GPU & CPU สำหรับ AI' },
      { symbol: 'AVGO', name: 'Broadcom', desc: 'AI networking & custom chips' },
      { symbol: 'TSM', name: 'TSMC', desc: 'ผลิตชิปรายใหญ่ที่สุดในโลก' },
      { symbol: 'ARM', name: 'Arm Holdings', desc: 'สถาปัตยกรรมชิป AI / Mobile' },
      { symbol: 'MRVL', name: 'Marvell Technology', desc: 'AI custom silicon & networking' },
      { symbol: 'INTC', name: 'Intel', desc: 'CPU & AI accelerator' },
      { symbol: 'QCOM', name: 'Qualcomm', desc: 'AI on-device / mobile chips' },
    ],
  },
  {
    id: 'ai-software',
    name: 'AI Software & Platform',
    icon: '🧠',
    color: 'text-blue-400',
    bg: 'bg-blue-500/15',
    stocks: [
      { symbol: 'MSFT', name: 'Microsoft', desc: 'Azure AI, Copilot, OpenAI partner' },
      { symbol: 'GOOGL', name: 'Alphabet', desc: 'Gemini, DeepMind, Google Cloud AI' },
      { symbol: 'AMZN', name: 'Amazon', desc: 'AWS Bedrock, Alexa AI' },
      { symbol: 'META', name: 'Meta Platforms', desc: 'Llama, AI-powered ads & Reels' },
      { symbol: 'CRM', name: 'Salesforce', desc: 'Einstein AI, Agentforce' },
      { symbol: 'PLTR', name: 'Palantir', desc: 'AI analytics & defense' },
      { symbol: 'NOW', name: 'ServiceNow', desc: 'AI workflow automation' },
      { symbol: 'SNOW', name: 'Snowflake', desc: 'AI data cloud & Cortex' },
    ],
  },
  {
    id: 'ai-pure',
    name: 'Pure-play AI',
    icon: '🤖',
    color: 'text-purple-400',
    bg: 'bg-purple-500/15',
    stocks: [
      { symbol: 'AI', name: 'C3.ai', desc: 'Enterprise AI platform' },
      { symbol: 'PATH', name: 'UiPath', desc: 'AI-powered automation (RPA)' },
      { symbol: 'SOUN', name: 'SoundHound AI', desc: 'Voice AI & conversational AI' },
      { symbol: 'BBAI', name: 'BigBear.ai', desc: 'AI analytics for government' },
      { symbol: 'UPST', name: 'Upstart', desc: 'AI lending platform' },
      { symbol: 'DOCS', name: 'Doximity', desc: 'AI for healthcare professionals' },
    ],
  },
  {
    id: 'ai-infra',
    name: 'AI Infrastructure & Data Center',
    icon: '🏗️',
    color: 'text-orange-400',
    bg: 'bg-orange-500/15',
    stocks: [
      { symbol: 'VRT', name: 'Vertiv', desc: 'Power & cooling สำหรับ data center' },
      { symbol: 'SMCI', name: 'Super Micro Computer', desc: 'AI server systems' },
      { symbol: 'DELL', name: 'Dell Technologies', desc: 'AI server & enterprise infra' },
      { symbol: 'ANET', name: 'Arista Networks', desc: 'AI data center networking' },
      { symbol: 'EQIX', name: 'Equinix', desc: 'Data center REIT' },
      { symbol: 'DLR', name: 'Digital Realty', desc: 'Data center REIT' },
    ],
  },
  {
    id: 'mag7',
    name: 'Magnificent 7',
    icon: '👑',
    color: 'text-yellow-400',
    bg: 'bg-yellow-500/15',
    stocks: [
      { symbol: 'AAPL', name: 'Apple', desc: 'Apple Intelligence, iPhone, Services' },
      { symbol: 'MSFT', name: 'Microsoft', desc: 'Azure, Office 365, Copilot' },
      { symbol: 'GOOGL', name: 'Alphabet', desc: 'Search, YouTube, Cloud' },
      { symbol: 'AMZN', name: 'Amazon', desc: 'AWS, E-commerce, Alexa' },
      { symbol: 'NVDA', name: 'NVIDIA', desc: 'GPU, AI, Data Center' },
      { symbol: 'META', name: 'Meta Platforms', desc: 'Facebook, Instagram, WhatsApp' },
      { symbol: 'TSLA', name: 'Tesla', desc: 'EV, FSD, Energy, Robotics' },
    ],
  },
  {
    id: 'dividend',
    name: 'หุ้นปันผลสูง (US)',
    icon: '💰',
    color: 'text-green-400',
    bg: 'bg-green-500/15',
    stocks: [
      { symbol: 'JNJ', name: 'Johnson & Johnson', desc: 'Healthcare, Dividend King' },
      { symbol: 'PG', name: 'Procter & Gamble', desc: 'Consumer goods, Dividend King' },
      { symbol: 'KO', name: 'Coca-Cola', desc: 'Beverages, Dividend King' },
      { symbol: 'PEP', name: 'PepsiCo', desc: 'Beverages & snacks' },
      { symbol: 'ABBV', name: 'AbbVie', desc: 'Pharma, high yield' },
      { symbol: 'O', name: 'Realty Income', desc: 'Monthly dividend REIT' },
      { symbol: 'VZ', name: 'Verizon', desc: 'Telecom, high yield' },
      { symbol: 'XOM', name: 'ExxonMobil', desc: 'Energy, strong dividend' },
    ],
  },
  {
    id: 'etf-popular',
    name: 'ETF ยอดนิยม',
    icon: '📊',
    color: 'text-cyan-400',
    bg: 'bg-cyan-500/15',
    stocks: [
      { symbol: 'SPY', name: 'SPDR S&P 500', desc: 'ดัชนี S&P 500' },
      { symbol: 'QQQ', name: 'Invesco QQQ', desc: 'ดัชนี Nasdaq-100' },
      { symbol: 'VTI', name: 'Vanguard Total Market', desc: 'ตลาดหุ้น US ทั้งหมด' },
      { symbol: 'ARKK', name: 'ARK Innovation', desc: 'หุ้น disruptive innovation' },
      { symbol: 'SOXX', name: 'iShares Semiconductor', desc: 'หุ้นเซมิคอนดักเตอร์' },
      { symbol: 'VGT', name: 'Vanguard IT', desc: 'หุ้นเทคโนโลยี' },
      { symbol: 'SCHD', name: 'Schwab US Dividend', desc: 'หุ้นปันผลคุณภาพ' },
      { symbol: 'VOO', name: 'Vanguard S&P 500', desc: 'ดัชนี S&P 500 (Vanguard)' },
    ],
  },
  {
    id: 'energy',
    name: 'พลังงาน',
    icon: '⚡',
    color: 'text-amber-400',
    bg: 'bg-amber-500/15',
    stocks: [
      { symbol: 'XOM', name: 'ExxonMobil', desc: 'น้ำมัน & แก๊ส รายใหญ่ที่สุดในสหรัฐ' },
      { symbol: 'CVX', name: 'Chevron', desc: 'น้ำมัน & แก๊ส ครบวงจร' },
      { symbol: 'COP', name: 'ConocoPhillips', desc: 'สำรวจ & ผลิตน้ำมัน' },
      { symbol: 'SLB', name: 'Schlumberger', desc: 'บริการขุดเจาะน้ำมัน' },
      { symbol: 'EOG', name: 'EOG Resources', desc: 'ผลิตน้ำมัน shale ชั้นนำ' },
      { symbol: 'NEE', name: 'NextEra Energy', desc: 'พลังงานหมุนเวียน อันดับ 1' },
      { symbol: 'ENPH', name: 'Enphase Energy', desc: 'ระบบ solar inverter' },
      { symbol: 'FSLR', name: 'First Solar', desc: 'แผงโซลาร์เซลล์' },
    ],
  },
  {
    id: 'space',
    name: 'อวกาศ & ดาวเทียม',
    icon: '🚀',
    color: 'text-indigo-400',
    bg: 'bg-indigo-500/15',
    stocks: [
      { symbol: 'RKLB', name: 'Rocket Lab', desc: 'จรวดส่งดาวเทียม Electron & Neutron' },
      { symbol: 'ASTS', name: 'AST SpaceMobile', desc: 'อินเทอร์เน็ตดาวเทียมตรงสู่มือถือ' },
      { symbol: 'BA', name: 'Boeing', desc: 'อากาศยาน & อวกาศ' },
      { symbol: 'LMT', name: 'Lockheed Martin', desc: 'ดาวเทียม, จรวด, อวกาศ' },
      { symbol: 'LUNR', name: 'Intuitive Machines', desc: 'ยานลงจอดดวงจันทร์' },
      { symbol: 'PL', name: 'Planet Labs', desc: 'ดาวเทียมสำรวจโลก' },
      { symbol: 'MNTS', name: 'Momentus', desc: 'ขนส่งอวกาศ last-mile' },
      { symbol: 'SPCE', name: 'Virgin Galactic', desc: 'ท่องเที่ยวอวกาศ' },
    ],
  },
  {
    id: 'defense',
    name: 'กลาโหม & สงคราม',
    icon: '🛡️',
    color: 'text-red-400',
    bg: 'bg-red-500/15',
    stocks: [
      { symbol: 'LMT', name: 'Lockheed Martin', desc: 'F-35, ขีปนาวุธ, ระบบป้องกัน' },
      { symbol: 'RTX', name: 'RTX (Raytheon)', desc: 'ขีปนาวุธ, เรดาร์, เครื่องยนต์เจ็ท' },
      { symbol: 'NOC', name: 'Northrop Grumman', desc: 'เครื่องบินทิ้งระเบิด B-21, ดาวเทียม' },
      { symbol: 'GD', name: 'General Dynamics', desc: 'รถถัง, เรือดำน้ำ, IT ทหาร' },
      { symbol: 'LHX', name: 'L3Harris', desc: 'ระบบสื่อสารทหาร, อิเล็กทรอนิกส์' },
      { symbol: 'PLTR', name: 'Palantir', desc: 'AI วิเคราะห์ข้อมูลกลาโหม' },
      { symbol: 'KTOS', name: 'Kratos Defense', desc: 'โดรนรบ, ระบบป้องกันขีปนาวุธ' },
      { symbol: 'AXON', name: 'Axon Enterprise', desc: 'กล้อง body cam, Taser, AI ตำรวจ' },
    ],
  },
  {
    id: 'food',
    name: 'อาหาร & เครื่องดื่ม',
    icon: '🍔',
    color: 'text-lime-400',
    bg: 'bg-lime-500/15',
    stocks: [
      { symbol: 'MCD', name: "McDonald's", desc: 'ฟาสต์ฟู้ดอันดับ 1 ของโลก' },
      { symbol: 'SBUX', name: 'Starbucks', desc: 'กาแฟ & เครื่องดื่มทั่วโลก' },
      { symbol: 'KO', name: 'Coca-Cola', desc: 'เครื่องดื่มอันดับ 1 ของโลก' },
      { symbol: 'PEP', name: 'PepsiCo', desc: 'เครื่องดื่ม & ขนมขบเคี้ยว' },
      { symbol: 'MDLZ', name: 'Mondelez', desc: 'ขนม Oreo, Cadbury, Toblerone' },
      { symbol: 'GIS', name: 'General Mills', desc: 'อาหาร Cheerios, Häagen-Dazs' },
      { symbol: 'HSY', name: 'Hershey', desc: 'ช็อกโกแลต & ขนมหวาน' },
      { symbol: 'COST', name: 'Costco', desc: 'ค้าส่ง & ค้าปลีกอาหาร' },
    ],
  },
  {
    id: 'software',
    name: 'ซอฟต์แวร์',
    icon: '💻',
    color: 'text-sky-400',
    bg: 'bg-sky-500/15',
    stocks: [
      { symbol: 'MSFT', name: 'Microsoft', desc: 'Windows, Office, Azure, Copilot' },
      { symbol: 'ORCL', name: 'Oracle', desc: 'Database, Cloud, ERP' },
      { symbol: 'CRM', name: 'Salesforce', desc: 'CRM อันดับ 1 ของโลก' },
      { symbol: 'ADBE', name: 'Adobe', desc: 'Photoshop, Premiere, Creative Cloud' },
      { symbol: 'NOW', name: 'ServiceNow', desc: 'IT workflow automation' },
      { symbol: 'INTU', name: 'Intuit', desc: 'TurboTax, QuickBooks, Mailchimp' },
      { symbol: 'PANW', name: 'Palo Alto Networks', desc: 'Cybersecurity platform' },
      { symbol: 'SHOP', name: 'Shopify', desc: 'E-commerce platform' },
    ],
  },
  {
    id: 'thai',
    name: 'หุ้นไทยยอดนิยม',
    icon: '🇹🇭',
    color: 'text-pink-400',
    bg: 'bg-pink-500/15',
    stocks: [
      { symbol: 'PTT.BK', name: 'PTT', desc: 'พลังงาน, ปิโตรเคมี' },
      { symbol: 'ADVANC.BK', name: 'AIS', desc: 'โทรคมนาคม' },
      { symbol: 'SCB.BK', name: 'SCB', desc: 'ธนาคาร' },
      { symbol: 'CPALL.BK', name: 'CP ALL', desc: '7-Eleven, ค้าปลีก' },
      { symbol: 'SCC.BK', name: 'SCG', desc: 'ปูนซีเมนต์, วัสดุก่อสร้าง' },
      { symbol: 'GULF.BK', name: 'Gulf Energy', desc: 'พลังงาน, โรงไฟฟ้า' },
      { symbol: 'AOT.BK', name: 'AOT', desc: 'สนามบิน' },
      { symbol: 'BDMS.BK', name: 'BDMS', desc: 'โรงพยาบาล' },
    ],
  },
  {
    id: 'thai-dividend',
    name: 'หุ้นไทยปันผลแจ่ม',
    icon: '💸',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/15',
    stocks: [
      { symbol: 'AP.BK', name: 'AP Thailand', desc: 'อสังหาฯ ปันผลสูง ~6-7%' },
      { symbol: 'TISCO.BK', name: 'TISCO', desc: 'ธนาคาร ปันผลสม่ำเสมอ ~5-7%' },
      { symbol: 'KKP.BK', name: 'Kiatnakin Phatra', desc: 'ธนาคาร+หลักทรัพย์ ปันผล ~5-7%' },
      { symbol: 'AMATA.BK', name: 'Amata', desc: 'นิคมอุตสาหกรรม ปันผล ~4-6%' },
      { symbol: 'SPALI.BK', name: 'Supalai', desc: 'อสังหาฯ ปันผลสูง ~6-8%' },
      { symbol: 'TTB.BK', name: 'ทหารไทยธนชาต', desc: 'ธนาคาร ปันผล ~4-5%' },
      { symbol: 'MTC.BK', name: 'Muangthai Capital', desc: 'สินเชื่อ ปันผล ~4-5%' },
      { symbol: 'TIDLOR.BK', name: 'เงินติดล้อ', desc: 'สินเชื่อ ปันผล ~3-4%' },
    ],
  },
  {
    id: 'crypto',
    name: 'คริปโตยอดนิยม',
    icon: '₿',
    color: 'text-orange-400',
    bg: 'bg-orange-500/15',
    stocks: [
      { symbol: 'BTC-USD', name: 'Bitcoin', desc: 'สกุลเงินดิจิทัลอันดับ 1' },
      { symbol: 'ETH-USD', name: 'Ethereum', desc: 'Smart Contract Platform' },
      { symbol: 'SOL-USD', name: 'Solana', desc: 'Blockchain ความเร็วสูง' },
      { symbol: 'BNB-USD', name: 'BNB', desc: 'Binance Chain Token' },
      { symbol: 'XRP-USD', name: 'XRP', desc: 'การชำระเงินข้ามประเทศ' },
      { symbol: 'ADA-USD', name: 'Cardano', desc: 'Proof-of-Stake Blockchain' },
      { symbol: 'AVAX-USD', name: 'Avalanche', desc: 'DeFi & Smart Contracts' },
      { symbol: 'DOGE-USD', name: 'Dogecoin', desc: 'Meme Coin ยอดนิยม' },
      { symbol: 'DOT-USD', name: 'Polkadot', desc: 'Cross-chain interoperability' },
      { symbol: 'LINK-USD', name: 'Chainlink', desc: 'Oracle เชื่อมข้อมูลจริงกับ Blockchain' },
    ],
  },
];

